# Generated by Django 5.1.4 on 2024-12-21 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appglob', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Content',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
